### PR TITLE
Remove the unnecessary .git directory addition

### PR DESCRIPTION
**Pull request by cyrille-gachot**
It is already in the gitignoredArr array from the gitignored.getGitignored() output

### CODE REVIEW

**Comment by patrickleet** [comment]
this was there for a reason, and that reason was that getGitignored didn't always return .git - I can't remember the details as honestly it's been a few years

**Comment by patrickleet** [comment]
it's doing that in two places?

**Comment by patrickleet** [comment]
@cyrille-gachot rebase for the new github actions pr pipeline to run

**Comment by cyrille-gachot** [comment]
Branch rebased

**Pull request merged**
